/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health_care;

import health_care.Admin_home;
import health_care.Health_Care_Database_Connection;
import health_care.Home;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class Admin_by_all_information extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public Admin_by_all_information() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("hospital.png")));
        setTitle("All Information Panel");
        conn=Health_Care_Database_Connection.ConnecrDb();
        refresh_doctor();
        refresh_patient();
        refresh_stuff();
        msg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_patient = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_stuff = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_doctor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        refresh_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        delete_doctor_btn = new javax.swing.JButton();
        update_doctor = new javax.swing.JButton();
        delete_patient = new javax.swing.JButton();
        update_patient = new javax.swing.JButton();
        delete_stuff = new javax.swing.JButton();
        update_stuff = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        s = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        send2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(table);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 590, 110));

        msg.setColumns(20);
        msg.setRows(5);
        jScrollPane5.setViewportView(msg);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 390, -1));

        send.setText("Send to patient");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 220, 40));

        table_patient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_patientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_patient);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 580, 340));

        table_stuff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_stuff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_stuffMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_stuff);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 620, 170));

        table_doctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_doctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_doctorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_doctor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 620, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("All Patient Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("All Doctor Information");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" All Stuff Information");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        jPanel1.add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 180, 50));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 180, 50));

        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 550, 180, 40));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 600, 180, 40));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        delete_doctor_btn.setText("Delete Doctor");
        delete_doctor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_doctor_btnActionPerformed(evt);
            }
        });

        update_doctor.setText("Update Doctor");
        update_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_doctorActionPerformed(evt);
            }
        });

        delete_patient.setText("Delete Patient");
        delete_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_patientActionPerformed(evt);
            }
        });

        update_patient.setText("Update Patient");
        update_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_patientActionPerformed(evt);
            }
        });

        delete_stuff.setText("Delete Stuff ");
        delete_stuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_stuffActionPerformed(evt);
            }
        });

        update_stuff.setText("Update Stuff ");
        update_stuff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_stuffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_doctor_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_stuff, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_stuff, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(delete_doctor_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(update_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(delete_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(update_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(delete_stuff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(update_stuff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 190, 330));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 30));
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, -1));
        jPanel3.add(dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department / Color");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, -1));
        jPanel3.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Serial");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 140, -1));
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 190, 330));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Send Message to Doctor or Patient");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        send2.setText("Send to doctor");
        send2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send2ActionPerformed(evt);
            }
        });
        jPanel1.add(send2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 220, 40));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(table1);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 590, 110));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("P");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 10, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("D");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 20, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_patientMouseClicked
        try{
            int row = table_patient.getSelectedRow();
            String Serial_=(table_patient.getModel().getValueAt(row, 0)).toString();

            String query = "select * from tbl_patient where Serial='"+Serial_+"'";
            PreparedStatement pst = conn.prepareStatement(query);

            ResultSet rs = pst.executeQuery();

            while(rs.next())
            {
                s.setText(rs.getString("Serial"));
                id.setText(rs.getString("P_id"));
                username.setText(rs.getString("P_username"));
                password.setText(rs.getString("P_password"));
                email.setText(rs.getString("P_email"));
                dc.setText(rs.getString("P_color"));
            }
            //JOptionPane.showMessageDialog(null, "Great");
            pst.close();

        }

        catch (Exception ef){
            JOptionPane.showMessageDialog(null, "Please refresh First");
        }
    }//GEN-LAST:event_table_patientMouseClicked

    private void table_stuffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_stuffMouseClicked
        try{
            int row = table_stuff.getSelectedRow();
            String Serial_=(table_stuff.getModel().getValueAt(row, 0)).toString();

            String query = "select * from tbl_stuff where Serial='"+Serial_+"'";
            pst = conn.prepareStatement(query);

            rs = pst.executeQuery();

            while(rs.next())
            {
                s.setText(rs.getString("Serial"));
                id.setText(rs.getString("S_id"));
                username.setText(rs.getString("S_username"));
                password.setText(rs.getString("S_password"));
                email.setText(rs.getString("S_email"));
                dc.setText(rs.getString("S_color"));
            }
            //JOptionPane.showMessageDialog(null, "Great");
            pst.close();

        }

        catch (Exception ef){
            JOptionPane.showMessageDialog(null, "Please refresh First");
        }
    }//GEN-LAST:event_table_stuffMouseClicked

    private void table_doctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_doctorMouseClicked
        try{
            int row = table_doctor.getSelectedRow();
            String Serial_=(table_doctor.getModel().getValueAt(row, 0)).toString();

            String query = "select * from tbl_dotor where Serial='"+Serial_+"'";
            PreparedStatement pst = conn.prepareStatement(query);

            ResultSet rs = pst.executeQuery();

            while(rs.next())
            {
                s.setText(rs.getString("Serial"));
                id.setText(rs.getString("D_id"));
                username.setText(rs.getString("D_username"));
                password.setText(rs.getString("D_password"));
                email.setText(rs.getString("D_email"));
                dc.setText(rs.getString("D_department"));
            }
            //JOptionPane.showMessageDialog(null, "Great");
            pst.close();

        }

        catch (Exception ef){
            JOptionPane.showMessageDialog(null, ef.getMessage());
        }
    }//GEN-LAST:event_table_doctorMouseClicked

    
    public void refresh_doctor(){
        try {
            String query="select * from tbl_dotor";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            
            table_doctor.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
            
            id.setText("");
            username.setText("");
            password.setText("");
            email.setText("");
            dc.setText("");
            s.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void refresh_patient(){
        try {
            String query="select * from tbl_patient";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            
            table_patient.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
            
            id.setText("");
            username.setText("");
            password.setText("");
            email.setText("");
            dc.setText("");
            s.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void refresh_stuff(){
        try {
            String query="select * from tbl_stuff";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            table_stuff.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
            
            id.setText("");
            username.setText("");
            password.setText("");
            email.setText("");
            dc.setText("");
            s.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void msg(){
        try {
            try {
            String query="select * from tbl_admin_doctor";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
            
            id.setText("");
            username.setText("");
            password.setText("");
            email.setText("");
            dc.setText("");
            s.setText("");
            msg.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        try {
            try {
            String query="select * from tbl_admin_patient";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
            
            id.setText("");
            username.setText("");
            password.setText("");
            email.setText("");
            dc.setText("");
            s.setText("");
            msg.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        refresh_doctor();
        refresh_patient();
        refresh_stuff();
        msg();
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Admin_home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void delete_doctor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_doctor_btnActionPerformed
        int action=JOptionPane.showConfirmDialog(null, "Do You Really Want To Remove This Doctor Id ?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
        if(action==0){
            try {
                String query="DELETE FROM tbl_dotor WHERE Serial='"+s.getText()+"' and D_id='"+id.getText()+"'and D_username='"+username.getText()+"' and D_department='"+dc.getText()+"'";
                pst = conn.prepareStatement(query);
                pst.execute();

                //JOptionPane.showMessageDialog(null, "Removed Successfully");

                pst.close();
            }
            catch(Exception ed){
                JOptionPane.showMessageDialog(null, ed.getMessage());
            }

        }

        refresh_doctor();
        refresh_patient();
        refresh_stuff();
    }//GEN-LAST:event_delete_doctor_btnActionPerformed

    private void update_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_doctorActionPerformed
        try
        {

            String query = "Update tbl_dotor set D_id ='"+id.getText()+"',D_username='"+username.getText()+"',D_password='"+password.getText()+"',D_email='"+email.getText()+"',D_department='"+dc.getText()+"' where Serial ='"+s.getText()+"'";
            pst = conn.prepareStatement(query);

            pst.execute();

            //JOptionPane.showMessageDialog(null, "Information modified");

            pst.close();

        } catch (Exception es) {
            es.printStackTrace();
        }

        refresh_doctor();
        refresh_patient();
        refresh_stuff();
    }//GEN-LAST:event_update_doctorActionPerformed

    private void delete_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_patientActionPerformed
        int action=JOptionPane.showConfirmDialog(null, "Do You Really Want To Remove This Patient Id ?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
        if(action==0){
            try {
                String query="DELETE FROM tbl_patient WHERE Serial='"+s.getText()+"' and P_id='"+id.getText()+"'and P_username='"+username.getText()+"' and P_color='"+dc.getText()+"'";
                pst = conn.prepareStatement(query);
                pst.execute();

                //JOptionPane.showMessageDialog(null, "Removed Successfully");

                pst.close();
            }
            catch(Exception ed){
                JOptionPane.showMessageDialog(null, ed.getMessage());
            }

        }

        refresh_doctor();
        refresh_patient();
        refresh_stuff();
    }//GEN-LAST:event_delete_patientActionPerformed

    private void update_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_patientActionPerformed
        try
        {

            String query = "Update tbl_patient set P_id ='"+id.getText()+"',P_username='"+username.getText()+"',P_password='"+password.getText()+"',P_email='"+email.getText()+"',P_color='"+dc.getText()+"' where Serial ='"+s.getText()+"'";
            pst = conn.prepareStatement(query);

            pst.execute();

            //JOptionPane.showMessageDialog(null, "Information modified");

            pst.close();

        } catch (Exception es) {
            JOptionPane.showMessageDialog(null, es.getMessage());
        }

        refresh_doctor();
        refresh_patient();
        refresh_stuff();
    }//GEN-LAST:event_update_patientActionPerformed

    private void delete_stuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_stuffActionPerformed
        int action=JOptionPane.showConfirmDialog(null, "Do You Really Want To Remove This Stuff Id ?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
        if(action==0){
            try {
                String query="DELETE FROM tbl_Stuff WHERE Serial='"+s.getText()+"' and S_id='"+id.getText()+"'and S_username='"+username.getText()+"' and S_color='"+dc.getText()+"'";
                pst = conn.prepareStatement(query);
                pst.execute();

                //JOptionPane.showMessageDialog(null, "Removed Successfully");

                pst.close();
            }
            catch(Exception ed){
                JOptionPane.showMessageDialog(null, ed.getMessage());
            }

        }

        refresh_doctor();
        refresh_patient();
        refresh_stuff();
    }//GEN-LAST:event_delete_stuffActionPerformed

    private void update_stuffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_stuffActionPerformed
        try
        {

            String query = "Update tbl_stuff set S_id ='"+id.getText()+"',S_username='"+username.getText()+"',S_password='"+password.getText()+"',S_email='"+email.getText()+"',S_color='"+dc.getText()+"' where Serial ='"+s.getText()+"'";
            pst = conn.prepareStatement(query);

            pst.execute();

            //JOptionPane.showMessageDialog(null, "Information modified");

            pst.close();

        } catch (Exception es) {
            JOptionPane.showMessageDialog(null, es.getMessage());
        }

        refresh_doctor();
        refresh_patient();
        refresh_stuff();
    }//GEN-LAST:event_update_stuffActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        String user=username.getText().toString();
        String ph=id .getText().toString();
        
        String d=dc.getText().toString();
        String m=msg.getText().toString();
        
        if(user.isEmpty()||ph.isEmpty()||d.isEmpty()||m.isEmpty()){
            JOptionPane.showMessageDialog(null, "You have to click specific patient to dend him a message");
        }
        else{
            
        try
	  {
					
					
					String query = " insert into tbl_admin_patient(phone , username, color, message,responce) values (?,?,?,?,?)";
					PreparedStatement pst = conn.prepareStatement(query);
					
					
                                        
					pst.setString(1,id.getText());
					pst.setString(2,username.getText());
					pst.setString(3,dc.getText());
					pst.setString(4,msg.getText());
                                        pst.setString(5,"Not Seen");
					
					pst.execute();
					pst.close();
					
					JOptionPane.showMessageDialog(null, "Message sent !!");
					msg();
                                        
					
				} catch (Exception es) {
					JOptionPane.showMessageDialog(null, es);
				}
    
        }
    }//GEN-LAST:event_sendActionPerformed

    private void send2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send2ActionPerformed
        String user=username.getText().toString();
        String ph=id .getText().toString();
        
        String d=dc.getText().toString();
        String m=msg.getText().toString();
        
        if(user.isEmpty()||ph.isEmpty()||d.isEmpty()||m.isEmpty()){
            JOptionPane.showMessageDialog(null, "You have to click specific doctor to dend him a message");
        }
        else{
            
        try
	  {
					
					
					String query = " insert into tbl_admin_doctor(phone , username, department, message,responce) values (?,?,?,?,?)";
					PreparedStatement pst = conn.prepareStatement(query);
					
					
                                        
					pst.setString(1,id.getText());
					pst.setString(2,username.getText());
					pst.setString(3,dc.getText());
					pst.setString(4,msg.getText());
                                        pst.setString(5,"Not Seen");
					
					pst.execute();
					pst.close();
					
					JOptionPane.showMessageDialog(null, "Message sent !!");
                                        msg();
					
				} catch (Exception es) {
					JOptionPane.showMessageDialog(null, es);
				}
    
        }
    }//GEN-LAST:event_send2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_by_all_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_by_all_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_by_all_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_by_all_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_by_all_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dc;
    private javax.swing.JButton delete_doctor_btn;
    private javax.swing.JButton delete_patient;
    private javax.swing.JButton delete_stuff;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea msg;
    private javax.swing.JTextField password;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTextField s;
    private javax.swing.JButton send;
    private javax.swing.JButton send2;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTable table_doctor;
    private javax.swing.JTable table_patient;
    private javax.swing.JTable table_stuff;
    private javax.swing.JButton update_doctor;
    private javax.swing.JButton update_patient;
    private javax.swing.JButton update_stuff;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
