/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health_care;

import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Aunshon
 */
public class Doctor_Register extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rst=null;
    PreparedStatement pst=null;
    public Doctor_Register() {
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("hospital.png")));
        setTitle("Doctor Register");
        initComponents();
        conn=Health_Care_Database_Connection.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        D_username_tf = new javax.swing.JTextField();
        D_email_tf = new javax.swing.JTextField();
        D_dep_tf = new javax.swing.JTextField();
        D_password_tf_n = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        New_Password_checkbox = new javax.swing.JCheckBox();
        D_password_tf = new javax.swing.JPasswordField();
        Conferm_Password_checkbox = new javax.swing.JCheckBox();
        D_sign_up_btn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        D_id_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/doctor (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, 40));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Information");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        jLabel7.setText("Phone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel8.setText("Username");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel10.setText("Dep.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/keyword (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 270));

        D_username_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_username_tfActionPerformed(evt);
            }
        });
        jPanel1.add(D_username_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 160, 30));

        D_email_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_email_tfActionPerformed(evt);
            }
        });
        jPanel1.add(D_email_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 160, 30));
        jPanel1.add(D_dep_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 160, 30));

        D_password_tf_n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D_password_tf_nMouseClicked(evt);
            }
        });
        jPanel1.add(D_password_tf_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 30));

        jLabel5.setText("New Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/is-less-than-mathematical-sign (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 70, 70));

        jPanel2.setBackground(new java.awt.Color(54, 112, 137));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Set Password");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(16, 30, 80, 20);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 100, 80));

        New_Password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Password_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(New_Password_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 30, 30));
        jPanel1.add(D_password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 230, 30));

        Conferm_Password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conferm_Password_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(Conferm_Password_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 30, 30));

        D_sign_up_btn.setText("Sign Up");
        D_sign_up_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_sign_up_btnActionPerformed(evt);
            }
        });
        jPanel1.add(D_sign_up_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Register");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel6.setText("Conferm Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));
        jPanel1.add(D_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new nd().setVisible(true);
        dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void D_username_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_username_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_D_username_tfActionPerformed

    private void D_password_tf_nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D_password_tf_nMouseClicked

    }//GEN-LAST:event_D_password_tf_nMouseClicked

    private void New_Password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Password_checkboxActionPerformed
        if(New_Password_checkbox.isSelected()==true){
            D_password_tf_n.setEchoChar((char)0);
            //Conferm_Password_tf.setEchoChar((char)0);
        }
        else{
            D_password_tf_n.setEchoChar('*');
            //Conferm_Password_tf.setEchoChar('*');
        }
    }//GEN-LAST:event_New_Password_checkboxActionPerformed

    private void Conferm_Password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conferm_Password_checkboxActionPerformed
        if(Conferm_Password_checkbox.isSelected()==true){
            //New_Password_tf.setEchoChar((char)0);
            D_password_tf.setEchoChar((char)0);
        }
        else{
            //New_Password_tf.setEchoChar('*');
            D_password_tf.setEchoChar('*');
        }
    }//GEN-LAST:event_Conferm_Password_checkboxActionPerformed

    public void reg(){
        try
	  {
					
					
					String query = " insert into tbl_dotor(D_id , D_username, D_password, D_department, D_email) values (?,?,?,?,?)";
					PreparedStatement pst = conn.prepareStatement(query);
					
					
                                        
					pst.setString(1,D_id_tf.getText());
					pst.setString(2,D_username_tf.getText());
					pst.setString(3,D_password_tf.getText());
					pst.setString(4,D_dep_tf.getText());
					pst.setString(5,D_email_tf.getText());
					
					pst.execute();
					pst.close();
					
					//JOptionPane.showMessageDialog(null, "Registered Successfully !!");
					new nd().setVisible(true);
                                        dispose();
					
				} catch (Exception es) {
					JOptionPane.showMessageDialog(null, es);
				}
    }
    private void D_sign_up_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_sign_up_btnActionPerformed

        String id=D_id_tf.getText().toString();
        String username=D_username_tf.getText().toString();
        String password=D_password_tf.getText().toString();
        String email=D_email_tf.getText().toString();
        String dep=D_dep_tf.getText().toString();
        String cpassword=D_password_tf_n.getText().toString();
                
        if(id.isEmpty()||username.isEmpty()||password.isEmpty()||email.isEmpty()||dep.isEmpty()||cpassword.isEmpty()
                ||password == null ? cpassword != null : !password.equals(cpassword)
                ){
            JOptionPane.showMessageDialog(null, "Please Fill Up All The Box Or Check The Password");
        }
        else{
                reg();
             }
    }//GEN-LAST:event_D_sign_up_btnActionPerformed

    private void D_email_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_email_tfActionPerformed
        String username=D_username_tf.getText().toString();
        String password=D_password_tf.getText().toString();
        String email=D_email_tf.getText().toString();
        String dep=D_dep_tf.getText().toString();
        String cpassword=D_password_tf_n.getText().toString();
        
        if(username.isEmpty()){
            JOptionPane.showMessageDialog(null, "Empty username");
        }
    }//GEN-LAST:event_D_email_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Conferm_Password_checkbox;
    private javax.swing.JTextField D_dep_tf;
    private javax.swing.JTextField D_email_tf;
    private javax.swing.JTextField D_id_tf;
    private javax.swing.JPasswordField D_password_tf;
    private javax.swing.JPasswordField D_password_tf_n;
    private javax.swing.JButton D_sign_up_btn;
    private javax.swing.JTextField D_username_tf;
    private javax.swing.JCheckBox New_Password_checkbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
