/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health_care;

import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Aunshon
 */
public class Doctor_Galary extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null,rr=null;
    PreparedStatement pst=null,p=null;
    String call_pass;
    String call_user;
    String call_id;
    String call_dep;
    
    
    public Doctor_Galary() {
        initComponents();
        
        conn=Health_Care_Database_Connection.ConnecrDb();
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("hospital.png")));
        setTitle("Doctor Gallary");
        
    }

    public Doctor_Galary(String u,String p,String i,String d){
        initComponents();
        
        call_pass=p;
        call_user=u;
        call_id=i;
        call_dep=d;
        username.setText(u);
        id.setText(i);
        dep.setText(d);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        app_req_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        app_list_table = new javax.swing.JTable();
        utime = new javax.swing.JTextField();
        udate = new javax.swing.JTextField();
        date_tf = new javax.swing.JTextField();
        day_tf = new javax.swing.JTextField();
        time_tf = new javax.swing.JTextField();
        uday = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        msg_box = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dep = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        serial = new javax.swing.JLabel();
        dresponce = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        dp_id = new javax.swing.JLabel();
        dp_user = new javax.swing.JLabel();
        dp_day = new javax.swing.JLabel();
        dp_time = new javax.swing.JLabel();
        dp_date = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        table5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbl_approved = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        pres_txt = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dp_duser = new javax.swing.JLabel();
        dp_did = new javax.swing.JLabel();
        dp_dept = new javax.swing.JLabel();
        D_responce = new javax.swing.JLabel();
        dp_pres = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        presc = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        prescribe = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        app_req_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        app_req_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app_req_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(app_req_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 670, 210));

        app_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        app_list_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                app_list_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(app_list_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 580, 210));

        utime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utimeActionPerformed(evt);
            }
        });
        jPanel1.add(utime, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 570, 80, 30));
        jPanel1.add(udate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 80, 30));
        jPanel1.add(date_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 80, 30));
        jPanel1.add(day_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 80, 30));
        jPanel1.add(time_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 80, 30));
        jPanel1.add(uday, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 80, 30));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 613, 80, 30));

        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, 80, 70));

        msg_box.setColumns(20);
        msg_box.setRows(5);
        jScrollPane3.setViewportView(msg_box);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 260, 80));

        jButton1.setText("Approve Appontment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 170, 30));

        jButton2.setText("Cancle Appontment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 170, 30));

        jLabel1.setText("Appontment Request");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setText("Your Appontment List");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, -1, -1));

        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, -1, -1));

        jLabel4.setText("Day Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, -1, -1));

        jLabel5.setText("Time");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, -1, -1));

        jLabel6.setText("Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, -1, -1));

        jLabel7.setText("Day Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, -1, -1));

        jLabel8.setText("Time");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, -1, -1));

        jLabel9.setText("Your Message");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, 20));

        jButton6.setText("Logout");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, 120, 30));

        jButton7.setText("Refresh");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 150, 30));

        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 130, 30));

        jLabel12.setText("Phone");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel13.setText("Username");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel10.setText("Department");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));
        jPanel1.add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 140, 30));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 180, 30));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 170, 30));

        serial.setForeground(new java.awt.Color(0, 153, 153));
        serial.setText("jLabel11");
        jPanel1.add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 70, 20));

        dresponce.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dresponce, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 510, 110));

        jLabel11.setText("Cancled Appointment");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        dp_id.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        dp_user.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        dp_day.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        dp_time.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        dp_date.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 650, 80, 30));

        table5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(table5);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 510, 100));

        msg.setColumns(20);
        msg.setRows(5);
        jScrollPane6.setViewportView(msg);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 260, 80));

        jButton3.setText("Seen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 170, 30));

        jLabel14.setText("Admin Message Detail");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        tbl_approved.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_approved.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_approvedMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tbl_approved);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 510, 120));

        jLabel15.setText("List of messages from admin");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        pres_txt.setColumns(20);
        pres_txt.setRows(5);
        jScrollPane7.setViewportView(pres_txt);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 280, 330));

        jLabel16.setText("Approved Apointments");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel17.setText("Prescreption Ditels");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 290, -1, -1));

        dp_duser.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_duser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        dp_did.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_did, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        dp_dept.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        D_responce.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(D_responce, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        dp_pres.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(dp_pres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        presc.setColumns(20);
        presc.setRows(5);
        jScrollPane9.setViewportView(presc);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 516, 260, 90));

        jLabel18.setText("Write Prescreption");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        prescribe.setText("Prescribe");
        prescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescribeActionPerformed(evt);
            }
        });
        jPanel1.add(prescribe, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 150, 30));

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 643, 130, 30));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jButton8ActionPerformed

    public void app_table_list_refresh(){
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()||
                dep.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username or Department text field \n You can not leave them empty");
            
        }
        else{
            try{
           String query = "select * from tbl_allapointment where D_id="+id.getText()+" and D_username='"+username.getText()+"'and D_department='"+dep.getText()+"' ";
           pst = conn.prepareStatement(query);
	   rs = pst.executeQuery();
			
	   app_list_table.setModel(DbUtils.resultSetToTableModel(rs));
	
           pst.execute();
           pst.close();
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        }
        msg_box.setText("");
        
    }
    public void approved_table_refresh(){
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()||
                dep.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username or Department text field \n You can not leave them empty");
            
        }
        else{
            try{
           String query = "select * from tbl_approved where D_id="+id.getText()+" and D_username='"+username.getText()+"'and D_department='"+dep.getText()+"' ";
           pst = conn.prepareStatement(query);
	   rs = pst.executeQuery();
			
	   tbl_approved.setModel(DbUtils.resultSetToTableModel(rs));
	
           pst.execute();
           pst.close();
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        }
        msg_box.setText("");
        
    }
    
    public void app_req(){
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()||
                dep.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username or Department text field \n You can not leave them empty");
            
        }
        else{
            try{
           String query = "select Serial,p_id,P_username,D_day,D_time,D_date,D_responce,P_responce from tbl_taken_app where D_id="+id.getText()+" and D_username='"+username.getText()+"'and D_department='"+dep.getText()+"' ";
           pst = conn.prepareStatement(query);
	   rs = pst.executeQuery();
			
	   app_req_table.setModel(DbUtils.resultSetToTableModel(rs));
	
           pst.execute();
           pst.close();
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        }
        msg_box.setText("");
    }
    public void cancle_fun(){
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username text field \n You can not leave them empty");
            
        }
        else{
            try{
           String query = "select Serial,P_id,P_username,D_date,D_time from tbl_cancle where D_id='"+id.getText()+"' and D_username='"+username.getText()+"'";
           pst = conn.prepareStatement(query);
	   rs = pst.executeQuery();
			
	   table4.setModel(DbUtils.resultSetToTableModel(rs));
	
           pst.execute();
           pst.close();
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        }
        msg_box.setText("");
    }
    
    public void msg(){
        try {
            try {
            String query="select * from tbl_admin_doctor where phone='"+id.getText()+"' and username='"+username.getText()+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            table5.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }}
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        app_table_list_refresh();
        app_req();
        cancle_fun();
        msg();
        approved_table_refresh();
        uday.setText("");
            utime.setText("");
            udate.setText("");
            day_tf.setText("");
            time_tf.setText("");
            date_tf.setText("");
            msg_box.setText("");
            presc.setText("");
            pres_txt.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new nd().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()||
                dep.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username or Department text field \n You can not leave them empty");
            
        }
        else{
            try{
            String query = "Update tbl_approved set D_responce='Approved' where Serial='"+serial.getText()+"'";
            pst = conn.prepareStatement(query);
	    pst.execute();
	    //JOptionPane.showMessageDialog(null, "Information modified");
	    pst.close();

        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            try
	       {
					
					
		String query = " insert into tbl_approved (Serial,P_id,P_username,D_id,D_username,D_department,D_day,D_time,D_date,D_responce,P_responce,prescreption) values (?,?,?,?,?,?,?,?,?,?,?,?)";
		PreparedStatement pst = conn.prepareStatement(query);
		                      
		pst.setString(1, serial.getText());
                pst.setString(2,dp_id.getText());
                pst.setString(3,dp_user.getText());
		pst.setString(4,id.getText());
		pst.setString(5,username.getText());
                pst.setString(6,dp_dept.getText());
                pst.setString(7,dp_day.getText());
                pst.setString(8,dp_time.getText());
		pst.setString(9,dp_date.getText());
		pst.setString(10,"Approved");
                pst.setString(11,"Waiting");
                pst.setString(12,"0");
					
		pst.execute();
		pst.close();
					
		//JOptionPane.showMessageDialog(null, "Product Successfully added");
					
					
				} catch (Exception es) {
					JOptionPane.showMessageDialog(null, es.getMessage());
				}
            try{
                String query = " delete from tbl_taken_app where Serial='"+serial.getText()+"'";
		PreparedStatement pst = conn.prepareStatement(query);
                pst.execute();
		pst.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        app_table_list_refresh();
        app_req();
        cancle_fun();
        msg();
        approved_table_refresh();
        uday.setText("");
            utime.setText("");
            udate.setText("");
            day_tf.setText("");
            time_tf.setText("");
            date_tf.setText("");
            msg_box.setText("");
            presc.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()||
                dep.getText().toString().isEmpty()||day_tf.getText().toString().isEmpty()||
                time_tf.getText().toString().isEmpty()||date_tf.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username or Department or day or time or date text field \n You can not leave them empty");
            
        }
        else{
            try{
            String query = " insert into tbl_allapointment (D_id,D_username,D_department,D_day,D_time,D_date) values (?,?,?,?,?,?)";
            pst=conn.prepareStatement(query);

            pst.setString(1, id.getText());
            pst.setString(2,username.getText());
            pst.setString(3,dep.getText());
            pst.setString(4,day_tf.getText());
            pst.setString(5,time_tf.getText());
            pst.setString(6,date_tf.getText());
            pst.execute();
            pst.close();

            //JOptionPane.showMessageDialog(null, "New Shedule Added");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        app_table_list_refresh();
        app_req();
        cancle_fun();
        msg();
        approved_table_refresh();
        uday.setText("");
            utime.setText("");
            udate.setText("");
            day_tf.setText("");
            time_tf.setText("");
            date_tf.setText("");
            msg_box.setText("");
            presc.setText("");

    }//GEN-LAST:event_add_btnActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()||
                dep.getText().toString().isEmpty()||uday.getText().toString().isEmpty()||
                utime.getText().toString().isEmpty()||udate.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username or Department or day or time or date text field \n You can not leave them empty");
            
        }
        else{
            try{
            String query = "Update tbl_allapointment set D_day='"+uday.getText()+"',D_time='"+utime.getText()+"',D_date='"+udate.getText()+"' where Serial ='"+serial.getText()+"'";
            pst = conn.prepareStatement(query);
	    pst.execute();
	    //JOptionPane.showMessageDialog(null, "Information modified");
	    pst.close();
            
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        app_table_list_refresh();
        app_req();
        cancle_fun();
        msg();
        approved_table_refresh();
        uday.setText("");
            utime.setText("");
            udate.setText("");
            day_tf.setText("");
            time_tf.setText("");
            date_tf.setText("");
            msg_box.setText("");
            presc.setText("");
    }//GEN-LAST:event_updateActionPerformed

    private void utimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utimeActionPerformed

    private void app_list_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app_list_tableMouseClicked
        try{
					int row = app_list_table.getSelectedRow();
					String Serial_=(app_list_table.getModel().getValueAt(row, 0)).toString();
					
					String query = "select * from tbl_allapointment where Serial='"+Serial_+"'";
					PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
					
					
					while(rs.next())
					{
                                                serial.setText(rs.getString("Serial"));
						id.setText(rs.getString("D_id"));
						username.setText(rs.getString("D_username"));
						dep.setText(rs.getString("D_department"));
						uday.setText(rs.getString("D_day"));
						utime.setText(rs.getString("D_time"));
                                                udate.setText(rs.getString("D_date"));
					}
					pst.close();
				}	
	
				catch (Exception ef){
				JOptionPane.showMessageDialog(null, ef.getMessage());
				}
    }//GEN-LAST:event_app_list_tableMouseClicked

    private void app_req_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_app_req_tableMouseClicked
        
        try{
					int row = app_req_table.getSelectedRow();
					String Serial_=(app_req_table.getModel().getValueAt(row, 0)).toString();
					
					String query = "select * from tbl_taken_app where Serial='"+Serial_+"'";
					PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
					
					
					while(rs.next())
					{
                                                serial.setText(rs.getString("Serial"));
						dp_id.setText(rs.getString("P_id"));
						dp_user.setText(rs.getString("P_username"));
						dp_day.setText(rs.getString("D_day"));
						dp_time.setText(rs.getString("D_time"));
                                                dp_date.setText(rs.getString("D_date"));
                                                dp_dept.setText(rs.getString("D_department"));
                                                dp_did.setText(rs.getString("D_id"));
                                                dp_duser.setText(rs.getString("D_username"));
                                                D_responce.setText(rs.getString("D_responce"));
                                                dp_pres.setText(rs.getString("P_responce"));
                                                
					}
                                        //JOptionPane.showMessageDialog(null, "YES");
					pst.close();
				}	
	
				catch (Exception ef){
				JOptionPane.showMessageDialog(null, ef.getMessage());
				}
    }//GEN-LAST:event_app_req_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(msg_box.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "you have to leave a meassage to cancle appointment leave the message in the message box");
        }
        else{
            try
	       {
					
					
		String query = " insert into tbl_cancle (Serial,D_id,D_username,P_id,P_username,D_date,D_time,D_message) values (?,?,?,?,?,?,?,?)";
		PreparedStatement pst = conn.prepareStatement(query);
		                      
		pst.setString(1, serial.getText());			
		pst.setString(2,id.getText());
		pst.setString(3,username.getText());
                pst.setString(4,dp_id.getText());
                pst.setString(5,dp_user.getText());
		pst.setString(6,dp_date.getText());
		pst.setString(7,dp_time.getText());
                pst.setString(8,msg_box.getText());
					
		pst.execute();
		pst.close();
					
		//JOptionPane.showMessageDialog(null, "Product Successfully added");
					
					
				} catch (Exception es) {
					JOptionPane.showMessageDialog(null, es.getMessage());
				}
            try{
                String query = " delete from tbl_taken_app where Serial='"+serial.getText()+"'";
		PreparedStatement pst = conn.prepareStatement(query);
                pst.execute();
		pst.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        msg_box.setText("");
        app_table_list_refresh();
        app_req();
        cancle_fun();
        approved_table_refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table4MouseClicked
        try{
					int row = table4.getSelectedRow();
					String Serial_=(table4.getModel().getValueAt(row, 0)).toString();
					
					String query = "select D_message from tbl_cancle where Serial='"+Serial_+"'";
					PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
					
					
					while(rs.next())
					{
                                                msg_box.setText(rs.getString("D_message"));
					}
                                        //JOptionPane.showMessageDialog(null, "Great");
					pst.close();
				}	
	
				catch (Exception ef){
				JOptionPane.showMessageDialog(null, ef.getMessage());
				}
    }//GEN-LAST:event_table4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int action=JOptionPane.showConfirmDialog(null, "Do You Really Want To Remove This from the Apointment List ?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
				if(action==0){
				try {
					String query="DELETE FROM tbl_allapointment WHERE D_id='"+id.getText()+"'and D_username='"+username.getText()+"' and D_department='"+dep.getText()+"'";
					pst = conn.prepareStatement(query);					
					pst.execute();
					
					//JOptionPane.showMessageDialog(null, "Removed Successfully");
						
					pst.close();
				}
				catch(Exception ed){
					JOptionPane.showMessageDialog(null, ed.getMessage());
				}
				
			}

        app_table_list_refresh();
        app_req();
        cancle_fun();
        msg();
        approved_table_refresh();
        uday.setText("");
            utime.setText("");
            udate.setText("");
            day_tf.setText("");
            time_tf.setText("");
            date_tf.setText("");
            msg_box.setText("");
            presc.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()||
                dep.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username or Department amd  text field \n You can not leave them empty");
            
        }
        else{
            try{
            String query = "Update tbl_admin_doctor set responce='Seen' where phone='"+id.getText()+"'";
            pst = conn.prepareStatement(query);
	    pst.execute();
	    //JOptionPane.showMessageDialog(null, "Information modified");
	    pst.close();

        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        app_table_list_refresh();
        app_req();
        cancle_fun();
        msg();
        approved_table_refresh();
        uday.setText("");
            utime.setText("");
            udate.setText("");
            day_tf.setText("");
            time_tf.setText("");
            date_tf.setText("");
            msg_box.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void table5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table5MouseClicked
        try{
					int row = table5.getSelectedRow();
					String Serial_=(table5.getModel().getValueAt(row, 0)).toString();
					
					String query = "select message from tbl_admin_doctor where Serial='"+Serial_+"'";
					PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
					
					
					while(rs.next())
					{
                                                msg.setText(rs.getString("message"));
					}
                                        //JOptionPane.showMessageDialog(null, "Great");
					pst.close();
				}	
	
				catch (Exception ef){
				JOptionPane.showMessageDialog(null, ef.getMessage());
				}
    }//GEN-LAST:event_table5MouseClicked

    private void prescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescribeActionPerformed
        if(id.getText().toString().isEmpty() || username.getText().toString().isEmpty()||
                dep.getText().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Check id or username or Department amd  text field \n You can not leave them empty");
            
        }
        else{
            try{
            String query = "Update tbl_approved set prescreption='"+presc.getText()+"' where D_id='"+id.getText()+"'";
            pst = conn.prepareStatement(query);
	    pst.execute();
	    //JOptionPane.showMessageDialog(null, "Information modified");
	    pst.close();
           approved_table_refresh();
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
        app_table_list_refresh();
        app_req();
        cancle_fun();
        msg();
        approved_table_refresh();
        uday.setText("");
            utime.setText("");
            udate.setText("");
            day_tf.setText("");
            time_tf.setText("");
            date_tf.setText("");
            msg_box.setText("");
            presc.setText("");
            pres_txt.setText("");
    }//GEN-LAST:event_prescribeActionPerformed

    private void tbl_approvedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_approvedMouseClicked
        try{
					int row = tbl_approved.getSelectedRow();
					String Serial_=(tbl_approved.getModel().getValueAt(row, 0)).toString();
					
					String query = "select * from tbl_approved where Serial='"+Serial_+"'";
					PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
					
					
					while(rs.next())
					{
                                                serial.setText(rs.getString("Serial"));
						dp_id.setText(rs.getString("P_id"));
						dp_user.setText(rs.getString("P_username"));
						dp_day.setText(rs.getString("D_day"));
						dp_time.setText(rs.getString("D_time"));
                                                dp_date.setText(rs.getString("D_date"));
                                                dp_dept.setText(rs.getString("D_department"));
                                                dp_did.setText(rs.getString("D_id"));
                                                dp_duser.setText(rs.getString("D_username"));
                                                D_responce.setText(rs.getString("D_responce"));
                                                dp_pres.setText(rs.getString("P_responce"));
                                                pres_txt.setText(rs.getString("prescreption"));
                                                
					}
                                        //JOptionPane.showMessageDialog(null, "YES");
					pst.close();
				}	
	
				catch (Exception ef){
				JOptionPane.showMessageDialog(null, ef.getMessage());
				}
    }//GEN-LAST:event_tbl_approvedMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(null, "Prescreption Is Ready To Print..");
        presc.setText("");
        pres_txt.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_Galary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_Galary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_Galary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_Galary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_Galary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel D_responce;
    private javax.swing.JButton add_btn;
    private javax.swing.JTable app_list_table;
    private javax.swing.JTable app_req_table;
    private javax.swing.JTextField date_tf;
    private javax.swing.JTextField day_tf;
    private javax.swing.JTextField dep;
    private javax.swing.JLabel dp_date;
    private javax.swing.JLabel dp_day;
    private javax.swing.JLabel dp_dept;
    private javax.swing.JLabel dp_did;
    private javax.swing.JLabel dp_duser;
    private javax.swing.JLabel dp_id;
    private javax.swing.JLabel dp_pres;
    private javax.swing.JLabel dp_time;
    private javax.swing.JLabel dp_user;
    private javax.swing.JLabel dresponce;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea msg;
    private javax.swing.JTextArea msg_box;
    private javax.swing.JTextArea pres_txt;
    private javax.swing.JTextArea presc;
    private javax.swing.JButton prescribe;
    private javax.swing.JLabel serial;
    private javax.swing.JTable table4;
    private javax.swing.JTable table5;
    private javax.swing.JTable tbl_approved;
    private javax.swing.JTextField time_tf;
    private javax.swing.JTextField udate;
    private javax.swing.JTextField uday;
    private javax.swing.JButton update;
    private javax.swing.JTextField username;
    private javax.swing.JTextField utime;
    // End of variables declaration//GEN-END:variables
}
