/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health_care;

import java.awt.Toolkit;

/**
 *
 * @author Aunshon
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("hospital.png")));
        setTitle("Home");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Admin_btn = new javax.swing.JButton();
        Doctor_btn = new javax.swing.JButton();
        Patient_btn = new javax.swing.JButton();
        Visitor_btn = new javax.swing.JButton();
        Stuff_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin_btn.setBackground(new java.awt.Color(0, 102, 102));
        Admin_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Admin_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/man2.png"))); // NOI18N
        Admin_btn.setText("Admin");
        Admin_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Admin_btn.setName(""); // NOI18N
        Admin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Admin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 310, 50));

        Doctor_btn.setBackground(new java.awt.Color(0, 102, 102));
        Doctor_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Doctor_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/doctor (2).png"))); // NOI18N
        Doctor_btn.setText("Doctor");
        Doctor_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Doctor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Doctor_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 310, 50));

        Patient_btn.setBackground(new java.awt.Color(0, 102, 102));
        Patient_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Patient_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/patient (1).png"))); // NOI18N
        Patient_btn.setText("Patient");
        Patient_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Patient_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Patient_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 310, 50));

        Visitor_btn.setBackground(new java.awt.Color(0, 102, 102));
        Visitor_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Visitor_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/visitor-identification (2).png"))); // NOI18N
        Visitor_btn.setText("Visitor");
        Visitor_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Visitor_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Visitor_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Visitor_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 310, 50));

        Stuff_btn.setBackground(new java.awt.Color(0, 102, 102));
        Stuff_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Stuff_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/employee (2).png"))); // NOI18N
        Stuff_btn.setText("Stuff");
        Stuff_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Stuff_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stuff_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Stuff_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 310, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 560));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_btnActionPerformed
        new Admin_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_Admin_btnActionPerformed

    private void Doctor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_btnActionPerformed
        new nd().setVisible(true);
        dispose();
    }//GEN-LAST:event_Doctor_btnActionPerformed

    private void Stuff_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stuff_btnActionPerformed
        new Stuff_Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_Stuff_btnActionPerformed

    private void Patient_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Patient_btnActionPerformed
        new Patient_Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_Patient_btnActionPerformed

    private void Visitor_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Visitor_btnActionPerformed
        new Visitor().setVisible(true);
        dispose();
    }//GEN-LAST:event_Visitor_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_btn;
    private javax.swing.JButton Doctor_btn;
    private javax.swing.JButton Patient_btn;
    private javax.swing.JButton Stuff_btn;
    private javax.swing.JButton Visitor_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
