/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health_care;

import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
public class Patient_Passwoerd_Recovery extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rst=null;
    PreparedStatement pst=null;
    public Patient_Passwoerd_Recovery() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("hospital.png")));
        setTitle("Patient Passwoerd Recovery");
        conn=Health_Care_Database_Connection.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        P_id_tf = new javax.swing.JTextField();
        P_username_tf = new javax.swing.JTextField();
        P_email_tf = new javax.swing.JTextField();
        P_color_tf = new javax.swing.JTextField();
        P_password_tf = new javax.swing.JPasswordField();
        congrem_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        message_box_tf = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        P_password_tf_n = new javax.swing.JPasswordField();
        New_Password_checkbox = new javax.swing.JCheckBox();
        Conferm_Password_checkbox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(145, 145, 88));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(P_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 160, 30));

        P_username_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_username_tfActionPerformed(evt);
            }
        });
        jPanel1.add(P_username_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 160, 30));
        jPanel1.add(P_email_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 160, 30));
        jPanel1.add(P_color_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 160, 30));
        jPanel1.add(P_password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 230, 30));

        congrem_btn.setText("Conferm");
        congrem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congrem_btnActionPerformed(evt);
            }
        });
        jPanel1.add(congrem_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Information");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        jLabel7.setText("Phone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/patient (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, 40));

        jLabel8.setText("Username");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel10.setText("Color");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/keyword3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 270));

        jLabel5.setText("New Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel6.setText("Conferm Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Write Report Down Here");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        message_box_tf.setColumns(20);
        message_box_tf.setRows(5);
        jScrollPane2.setViewportView(message_box_tf);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 350, 150));

        send.setText("Send  To Admin");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 130, 30));

        jButton2.setText("Admin Update");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 120, 30));

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 130, 30));

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 110, 30));

        jPanel2.setBackground(new java.awt.Color(158, 118, 0));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recovery");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 30, 70, 20);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, 80));

        P_password_tf_n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_password_tf_nMouseClicked(evt);
            }
        });
        jPanel1.add(P_password_tf_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 30));

        New_Password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Password_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(New_Password_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 30, 30));

        Conferm_Password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conferm_Password_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(Conferm_Password_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/back.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 70, 70));

        jButton5.setText("Help");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 120, 30));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_username_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_username_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P_username_tfActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void P_password_tf_nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_password_tf_nMouseClicked

    }//GEN-LAST:event_P_password_tf_nMouseClicked

    private void New_Password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Password_checkboxActionPerformed
        if(New_Password_checkbox.isSelected()==true){
            P_password_tf_n.setEchoChar((char)0);
            //Conferm_Password_tf.setEchoChar((char)0);
        }
        else{
            P_password_tf_n.setEchoChar('*');
            //Conferm_Password_tf.setEchoChar('*');
        }
    }//GEN-LAST:event_New_Password_checkboxActionPerformed

    private void Conferm_Password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conferm_Password_checkboxActionPerformed
        if(Conferm_Password_checkbox.isSelected()==true){
            //New_Password_tf.setEchoChar((char)0);
            P_password_tf.setEchoChar((char)0);
        }
        else{
            //New_Password_tf.setEchoChar('*');
            P_password_tf.setEchoChar('*');
        }
    }//GEN-LAST:event_Conferm_Password_checkboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void change() {
       
        try {
            String query="update tbl_patient set P_password='"+P_password_tf.getText()+"' WHERE P_id='"+P_id_tf.getText()+"' and P_username='"+P_username_tf.getText()+"' and P_email='"+P_email_tf.getText()+"' and P_color='"+P_color_tf.getText()+"'";
            pst=conn.prepareStatement(query);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Password Changed Successfully");
            new Patient_Login().setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void congrem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congrem_btnActionPerformed
        String username=P_username_tf.getText().toString();
        String password=P_password_tf_n.getText().toString();
        String email=P_email_tf.getText().toString();
        String dep=P_color_tf.getText().toString();
        String cpassword=P_password_tf.getText().toString();
        
        if(username.isEmpty()||password.isEmpty()||email.isEmpty()||dep.isEmpty()||cpassword.isEmpty()
                ||password == null ? cpassword != null : !password.equals(cpassword)
                ){
            JOptionPane.showMessageDialog(null, "Please Fill Up All The Box Or Check The Password");
        }
        else{
                try {
                    String a="select * from tbl_patient where P_id='"+P_id_tf.getText()+"' and P_username='"+P_username_tf.getText()+"' and P_email='"+P_email_tf.getText()+"' and P_color='"+P_color_tf.getText()+"'";
                    pst=conn.prepareStatement(a);
                    rst=pst.executeQuery();
                    
                if(rst.next()){
                    change();
                }
                else{
                    
                    JOptionPane.showMessageDialog(null, "Your Information Doesn't Matches");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
             }
    }//GEN-LAST:event_congrem_btnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(null, "If you want to set new password , then fill up all the boxes with right information and fill up password boxes and hit conferm ,OR,"
                + "\n if you forget some of your information OR \n You have Any Query then fill up your email and write the  message in the message box , hit Send To Admin and wait for admin replay"
                + "\n For admin replay fill up the email box and hit Admin Update");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void send_message(){
        try {
            String query=" insert into tbl_message(email,message) values (?,?)";
            pst = conn.prepareStatement(query);
            
            pst.setString(1, P_email_tf.getText());
            pst.setString(2, message_box_tf.getText());
            
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Message Sent Successfully");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        String email=P_email_tf.getText().toString();
        String message=message_box_tf.getText().toString();
        String e=P_username_tf.getText().toString();
        
        if(email.isEmpty()||message.isEmpty()){
            JOptionPane.showMessageDialog(null, "You Must Fill Up Both Email and Message box Or You can't send Message to Admin");
        }
        else{
                try {
                    String a="select * from tbl_patient where P_email='"+P_email_tf.getText()+"'";
                    pst=conn.prepareStatement(a);
                    rst=pst.executeQuery();
                    
                if(rst.next()){
                    send_message();
                }
                else{
                    
                    JOptionPane.showMessageDialog(null, "Email Does not Exist");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            }
    }//GEN-LAST:event_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_Passwoerd_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_Passwoerd_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_Passwoerd_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_Passwoerd_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_Passwoerd_Recovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Conferm_Password_checkbox;
    private javax.swing.JCheckBox New_Password_checkbox;
    private javax.swing.JTextField P_color_tf;
    private javax.swing.JTextField P_email_tf;
    private javax.swing.JTextField P_id_tf;
    private javax.swing.JPasswordField P_password_tf;
    private javax.swing.JPasswordField P_password_tf_n;
    private javax.swing.JTextField P_username_tf;
    private javax.swing.JButton congrem_btn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea message_box_tf;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables

    
}
