/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health_care;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

import javax.swing.*;
import java.sql.*;

public class Stuff_Password_Recovery extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rst=null;
    PreparedStatement pst=null;
    public Stuff_Password_Recovery() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("hospital.png")));
        setTitle("Stuff Passwoerd Recovery");
        conn=Health_Care_Database_Connection.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        S_password_tf_n = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        S_password_tf = new javax.swing.JPasswordField();
        Password_change_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Conferm_Password_checkbox = new javax.swing.JCheckBox();
        New_Password_checkbox = new javax.swing.JCheckBox();
        S_color_tf = new javax.swing.JTextField();
        S_email_tf = new javax.swing.JTextField();
        S_username_tf = new javax.swing.JTextField();
        S_id_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/employee (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, 40));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Information");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Color");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/keyword (4).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 270));

        S_password_tf_n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_password_tf_nMouseClicked(evt);
            }
        });
        jPanel1.add(S_password_tf_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Conferm Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));
        jPanel1.add(S_password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 230, 30));

        Password_change_btn.setText("Conferm");
        Password_change_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_change_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Password_change_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/angle-pointing-to-left.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 70, 70));

        jPanel2.setBackground(new java.awt.Color(96, 26, 61));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recovery");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 30, 70, 20);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, 80));

        Conferm_Password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conferm_Password_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(Conferm_Password_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 30, 30));

        New_Password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Password_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(New_Password_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 30, 30));
        jPanel1.add(S_color_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 160, 30));
        jPanel1.add(S_email_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 160, 30));

        S_username_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_username_tfActionPerformed(evt);
            }
        });
        jPanel1.add(S_username_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 160, 30));
        jPanel1.add(S_id_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 160, 30));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S_password_tf_nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_password_tf_nMouseClicked

    }//GEN-LAST:event_S_password_tf_nMouseClicked

    private void Conferm_Password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conferm_Password_checkboxActionPerformed
        if(Conferm_Password_checkbox.isSelected()==true){
            //New_Password_tf.setEchoChar((char)0);
            S_password_tf.setEchoChar((char)0);
        }
        else{
            //New_Password_tf.setEchoChar('*');
            S_password_tf.setEchoChar('*');
        }
    }//GEN-LAST:event_Conferm_Password_checkboxActionPerformed

    private void New_Password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Password_checkboxActionPerformed
        if(New_Password_checkbox.isSelected()==true){
            S_password_tf_n.setEchoChar((char)0);
            //Conferm_Password_tf.setEchoChar((char)0);
        }
        else{
            S_password_tf_n.setEchoChar('*');
            //Conferm_Password_tf.setEchoChar('*');
        }
    }//GEN-LAST:event_New_Password_checkboxActionPerformed

    private void S_username_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_username_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_username_tfActionPerformed

    private void change() {
       
        try {
            String query="update tbl_stuff set S_password='"+S_password_tf.getText()+"' WHERE 1";
            pst=conn.prepareStatement(query);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Password Changed Successfully");
            new Stuff_Login().setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void Password_change_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_change_btnActionPerformed
        String username=S_username_tf.getText().toString();
        String password=S_password_tf_n.getText().toString();
        String email=S_email_tf.getText().toString();
        String dep=S_color_tf.getText().toString();
        String cpassword=S_password_tf.getText().toString();
        
        if(username.isEmpty()||password.isEmpty()||email.isEmpty()||dep.isEmpty()||cpassword.isEmpty()
                ||password == null ? cpassword != null : !password.equals(cpassword)
                ){
            JOptionPane.showMessageDialog(null, "Please Fill Up All The Box Or Check The Password");
        }
        else{
                try {
                    String a="select * from tbl_stuff where S_id='"+S_id_tf.getText()+"' and S_username='"+S_username_tf.getText()+"' and S_email='"+S_email_tf.getText()+"' and S_color='"+S_color_tf.getText()+"'";
                    pst=conn.prepareStatement(a);
                    rst=pst.executeQuery();
                    
                if(rst.next()){
                    change();
                }
                else{
                    
                    JOptionPane.showMessageDialog(null, "Your Information Doesn't Matches");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
             }
    }//GEN-LAST:event_Password_change_btnActionPerformed

    /*private void send_message(){
        try {
            String query=" insert into tbl_message(email,message) values (?,?)";
            pst = conn.prepareStatement(query);
            
            pst.setString(1, S_email_tf.getText());
            pst.setString(2, S_message_tf.getText());
            
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Message Sent Successfully");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stuff_Password_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stuff_Password_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stuff_Password_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stuff_Password_Recovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stuff_Password_Recovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Conferm_Password_checkbox;
    private javax.swing.JCheckBox New_Password_checkbox;
    private javax.swing.JButton Password_change_btn;
    private javax.swing.JTextField S_color_tf;
    private javax.swing.JTextField S_email_tf;
    private javax.swing.JTextField S_id_tf;
    private javax.swing.JPasswordField S_password_tf;
    private javax.swing.JPasswordField S_password_tf_n;
    private javax.swing.JTextField S_username_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
