/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health_care;

import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
public class stuff_home extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public stuff_home() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().createImage(getClass().getResource("hospital.png")));
        setTitle("Stuff Home");
        conn=Health_Care_Database_Connection.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        old_password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        S_password_tf_n = new javax.swing.JPasswordField();
        c_password_tf = new javax.swing.JPasswordField();
        congrem_btn = new javax.swing.JButton();
        New_Password_checkbox = new javax.swing.JCheckBox();
        Conferm_Password_checkbox = new javax.swing.JCheckBox();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextArea();
        apply_for_leave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Old Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 30));

        jLabel5.setText("New Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        S_password_tf_n.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                S_password_tf_nMouseClicked(evt);
            }
        });
        jPanel1.add(S_password_tf_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 230, 30));
        jPanel1.add(c_password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 230, 30));

        congrem_btn.setText("Conferm");
        congrem_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                congrem_btnActionPerformed(evt);
            }
        });
        jPanel1.add(congrem_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 30));

        New_Password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Password_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(New_Password_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 30, 30));

        Conferm_Password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conferm_Password_checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(Conferm_Password_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 30, 30));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Username");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 70, -1));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 190, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phone");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 30, 200, 30));

        msg.setColumns(20);
        msg.setRows(5);
        jScrollPane1.setViewportView(msg);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 370, -1));

        apply_for_leave.setText("Apply For Leave");
        apply_for_leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apply_for_leaveActionPerformed(evt);
            }
        });
        jPanel1.add(apply_for_leave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 170, 30));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 560, 200));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("All Appliactions");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 120, 20));

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 130, 40));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 120, 40));

        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 120, 40));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 530));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S_password_tf_nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_S_password_tf_nMouseClicked

    }//GEN-LAST:event_S_password_tf_nMouseClicked

    private void change() {
       
        try {
            String query="update tbl_Stuff set S_password='"+c_password_tf.getText()+"' WHERE S_id='"+id.getText()+"' and S_username='"+username.getText()+"' and S_email='"+email.getText()+"'";
            pst=conn.prepareStatement(query);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Password Changed Successfully");
            new Stuff_Login().setVisible(true);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    private void congrem_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_congrem_btnActionPerformed
        String user=username.getText().toString();
        String pass=S_password_tf_n.getText().toString();
        String mail=email.getText().toString();
        String cpassword=c_password_tf.getText().toString();

        if(user.isEmpty()||pass.isEmpty()||mail.isEmpty()||cpassword.isEmpty()
            ||pass == null ? cpassword != null : !pass.equals(cpassword)
        ){
            JOptionPane.showMessageDialog(null, "Please Fill Up All The Box Or Check The Password");
        }
        else{
            try {
                String a="select * from tbl_stuff where S_id='"+id.getText()+"' and S_username='"+username.getText()+"' and S_email='"+email.getText()+"'";
                pst=conn.prepareStatement(a);
                rs=pst.executeQuery();

                if(rs.next()){
                    change();
                }
                else{

                    JOptionPane.showMessageDialog(null, "Your Information Doesn't Matches");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_congrem_btnActionPerformed

    private void New_Password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Password_checkboxActionPerformed
        if(New_Password_checkbox.isSelected()==true){
            S_password_tf_n.setEchoChar((char)0);
            //Conferm_Password_tf.setEchoChar((char)0);
        }
        else{
            S_password_tf_n.setEchoChar('*');
            //Conferm_Password_tf.setEchoChar('*');
        }
    }//GEN-LAST:event_New_Password_checkboxActionPerformed

    private void Conferm_Password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conferm_Password_checkboxActionPerformed
        if(Conferm_Password_checkbox.isSelected()==true){
            //New_Password_tf.setEchoChar((char)0);
            c_password_tf.setEchoChar((char)0);
        }
        else{
            //New_Password_tf.setEchoChar('*');
            c_password_tf.setEchoChar('*');
        }
    }//GEN-LAST:event_Conferm_Password_checkboxActionPerformed

    public void reg(){
        try
	  {
					
					
					String query = " insert into tbl_stuff_application(S_id , S_username, S_email,S_message,permission) values (?,?,?,?,?)";
					PreparedStatement pst = conn.prepareStatement(query);
					
						
                                        pst.setString(1,id.getText());
					pst.setString(2,username.getText());
					pst.setString(3,email.getText());
                                        pst.setString(4,msg.getText());
                                        pst.setString(5,"Waiting");
					
					pst.execute();
					pst.close();
					
					//JOptionPane.showMessageDialog(null, "Registered Successfully !!");
					refresh();
					
				} catch (Exception es) {
					JOptionPane.showMessageDialog(null, es);
				}
    }
    
    private void apply_for_leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apply_for_leaveActionPerformed
        String user=username.getText().toString();
        String i=id.getText().toString();
        String mail=email.getText().toString();
        String m=msg.getText().toString();

        if(user.isEmpty()||i.isEmpty()||mail.isEmpty()||m.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Fill Up All The Box of your personal information");
        }
        else{
            reg();
        }
    }//GEN-LAST:event_apply_for_leaveActionPerformed

    public void refresh(){
        
        
        try {
            String query="select * from tbl_stuff_application where S_id='"+id.getText()+"' and S_username='"+username.getText()+"' and S_email='"+email.getText()+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            
            table.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
            rs.close();
            msg.setText("");
            old_password.setText("");
            S_password_tf_n.setText("");
            c_password_tf.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String user=username.getText().toString();
        String i=id.getText().toString();
        String mail=email.getText().toString();
        

        if(user.isEmpty()||i.isEmpty()||mail.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Fill Up id , Username and email box");
        }
        else{
            refresh();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Stuff_Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stuff_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stuff_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stuff_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stuff_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stuff_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Conferm_Password_checkbox;
    private javax.swing.JCheckBox New_Password_checkbox;
    private javax.swing.JPasswordField S_password_tf_n;
    private javax.swing.JButton apply_for_leave;
    private javax.swing.JPasswordField c_password_tf;
    private javax.swing.JButton congrem_btn;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea msg;
    private javax.swing.JTextField old_password;
    private javax.swing.JTable table;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
